---
title: "Лабораторная работа №7"
---

# Трансляция конференции с Positive Hack Days "Погружение в метавселенные"

## Что такое метавселенная?

> Метавселенная - это виртуальное совместное пространство, созданное в результате конвергенции и физического мира. Этот термин был введёнписателем-фантастом Нилом Стивенсоном в его романе 1992 года "Снежная лавина".

## С чего всё начиналось?

Second life - виртуальный мир, созданный компанией Linden Lab в 2003 году, позволябщий пользователям взаимодействовать друг с другом и исследовать виртуальный мир. Имеет процветающую экономику с собственной виртуальной валютой Linden Dollar.

Sansar - после закрытия Second life компания Linden Lab в 2017 году разработала платформу Sansar. Здесь можно было создавать от игровых миров до спектаклей и выставок. Платформа также позволяет пользователям зарабатывать деньги, продавая созданные ими виртуальные товары и услуги.

## Какие бывают метавселенные?

1.  Платформозависимые (VRChat)
2.  Кроссплатформенные (The Spatial)
3.  Децентрализованные (Decentraland)
4.  Централизованные (Roblox)
5.  Узконаправленные (Sense Tower)
6.  Универсальные (Somnium Space)

## Факты

-   120+ млрд: инвестиции в пространство в метавселенной вдвое превысили за 2021 г.
-   \~\$5 трлн вложений в метавселенные в 2021 г.
-   59% потребителей готовы перенести свою повседневную деятельность в метавселенную
-   57% компаний, знающих о метавселенных, заявляют о готовности интегрироваться
-   в метавселенные активно внедряют свои продукты крупные бренды

## Проверка 4
